#!/bin/bash


# content to look for (from $HOME)
folders=(
    documents
    downloads
    pictures
    repositories
    stuff
    training
)  # data, music & videos folders are too big


save() {
    # gathering required folders' archives into a temporary folder
    cd data || exit 1
    tempdir="qzd${RANDOM}ase"
    mkdir "$tempdir"
    cd "$tempdir"
    archive="save$(date '+_%Y_%m_%d').zip"

    # actually compressing data
    for folder in "${folders[@]}"
    do
        tar --dereference --gzip --verbose \
            -cf "${folder}.tar.gz" \
            "../../${folder}"
    done

    # gathering these tarballs into a single zip file
    zip "$archive" ./*.tar.gz

    # moving from tempdir to data dump folder and removing tempdir
    rm ./*.tar.gz
    mv "$archive" ..
    cd ..
    rmdir "$tempdir"
}


load() {
    # uncompressing last archive into a temporary directory
    # TODO need that `--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r \` flag ?
    cd data || exit 1
    archive=$(ls save_* | tail -n 1)
    if [ -z "$archive" ]
    then
        echo 'No archive in found ~/data. Aborting.'
        exit 1
    fi
    tempdir="qzd${RANDOM}ase"
    mkdir "$tempdir"
    unzip "$archive" -d "$tempdir"
    cd "$tempdir" || exit 1

    # actually merging files and folders
    for folder in "${folders[@]}"
    do
        tar -zxf "${folder}.tar.gz"
        rsync \
            --archive \
            --compress \
            --delete-during \
            --delete-excluded \
            --partial \
            --progress \
            --verbose \
            "./${folder}/" \
            "${HOME}/${folder}"
    done

    cd ..
    rm -rf "$tempdir"
}


flat() {
    # TODO make sure the backup archive is encrypted
    exit 1

    scp -B "$archive" "${USER}@${FLAT}:/home/${USER}/data"
}


help() {
    # display help (rather self-explanatory ¯\_(ツ)_/¯)
    printf "Available options:
    * help: Displays this help
    * flat: move the latest (daily) folder to the flatshare
    * fix:  try to fix permissions issues
    * load: unzips last archive from ~/data
    * save: archives folders to ~/data\n"
}


cd "$HOME" || exit

if [ -z "$1" ]
then
    help
else
    time "$1"
    echo $?
fi
