#!/bin/bash


# https://korben.info/effacer-vraiment-disque-dur-de-revendre-donner.html

if [ -z "$1"]
then
    echo "Please provide a disk to wipe"
    exit
fi

dd if=/dev/zero of="/dev/${$1}"
dd if=/dev/urandom of="/dev/${$1}"
